### ISSUE TITLE
Hide Armor Trims Flag not working properly

### ISSUE THREAD

**Issue by Veyjinn** [Bestem0r/VillagerMarket#14]
Hello! A while ago, I informed you about an issue related to armor trims. 
Just a quick reminder of what this bug entails: The armor trim hide flag is being ignored by the Villager Market. So even though armor shouldn't show trims, Villager Market ignores the flag and makes the trim flag reappear after reloading  / restarting the server.

This inconsistency significantly impacts my server. I hope this issue will be resolved as soon as possible. Thanks for reading, cheers!

https://github.com/Bestem0r/VillagerMarket/assets/59097595/174eb9f0-5ee2-4818-ad7f-de901a56c70d

**Comment by Bestem0r** [comment]
Hi there! Sorry for not fixing this yet. I will take a look at it and send you a BETA build as soon as I've fixed it!
