### ISSUE TITLE
[FEATURE REQUEST] Add variable for maxShopsPerPlayer in config.yml

### ISSUE THREAD

**Issue by Grzybol** [Bestem0r/VillagerMarket#18]
Please add variable for maxShopsPerPlayer in config.yml, so whale players cannot buy all available villagers.

**Comment by HyPeRXKo** [comment]
Hi! I honestly though that was already in the plugin, same thing as Grzy say, if you use pre-placed shops players can rent, they can just rent all of them and it's a bit of a problem :(

**Comment by Bestem0r** [comment]
Hi again @Grzybol! 
As @HyPeRXKo says, this is indeed already a feature in VillagerMarket, but using permissions instead of an config option. You can set max shops per player by giving the `villagermarket.max_shops.<amount>` permission.

**Comment by Grzybol** [comment]
My bad now it works great, thanks!
