### ISSUE TITLE
Shops disapear after restart

### ISSUE THREAD

**Issue by CptGummiball** [Bestem0r/VillagerMarket#23]
Shops sometimea disappear randomly after restarts. Sometimes it happens and sometimes it doesn't. In addition, Villagermarket in version 1.11.7 creates shops multiple times as yml under several UUIDs. We have now deleted all duplicates and hope that it is at least temporarily fixed. We're continuing to monitor it, but it seems to happen especially when the save interval is set very low.

**Comment by Bestem0r** [comment]
When are shops created multiple times? Are you using the `/vm regen` command? Also, shops shouldn't despawn, since Villagers don't despawn.

**Comment by CptGummiball** [comment]
The duplication Bug is gone since we've changed the save interval back to 10 minutes.
Diaspearing Shop could be caused by Citizens. When i changed one shop to a citizen NPC after restart all other Shops disapear.

**Comment by CptGummiball** [comment]
I'm closing the issue. It has nothing to do with VillagerMarket. The problem has another source. Not only the shops disappear but also other entities. If you want, I'll let you know, but once we've found a solution, you can probably use it as an FAQ.
