### ISSUE TITLE
Shops may be lost under certain circumstances

### ISSUE THREAD

**Issue by CptGummiball** [Bestem0r/VillagerMarket#26]
VM 1.11.7 and 1.12.1

Shops can definitely be lost due to natural or manual despawn events. After that they can no longer be restored. A possible solution would be to generate the shops using the yamls every time the plugin is reloaded or the server starts instead of hooking the shops into the fixed Villager entities. So it doesn't matter whether they are deleted during the session.

**Comment by CptGummiball** [comment]
When Villagermarket tries to restore the shops, the old entity UUID is not restored but a new Villager with a new UUID is created and Villagermarket cannot hook into it properly.

**Comment by CptGummiball** [comment]
Seems to be a problem with a few Spigot builds. Couldn't reproduce it with the current 1.21.1 build.

**Comment by Bestem0r** [comment]
Yeah, this is what the `/vm generate` command is for, which used to run automatically on restart. Problem is that it's hard for the plugin to know if an entity is despawned or just not loaded yet. So in many cases it will create duplicate shops

**Comment by CptGummiball** [comment]
I believe the problem was that for some reason Spigot thought that the UUID already existed and so a new entity was created with a different UUID.
