### ISSUE TITLE
Console errors after updating to Paper 1.20.1 and VillagerMarket 1.11.6

### ISSUE THREAD

**Issue by xStellarZ** [Bestem0r/VillagerMarket#7]
They ~~seem to be~~ are definitely related to the random shop discounts.
![image](https://github.com/Bestem0r/VillagerMarket/assets/75229701/5bda7a05-797f-48f2-8384-8ecd44e62cea)

**Comment by Bestem0r** [comment]
Thanks for reporting. Will fix
